### ISSUE TITLE
Ecstatic script doesn't support ubuntu.

### ISSUE THREAD

**Issue by vmariano** [guillep/ecstatic#1]
Following the tutorial describe in [first side](http://guillep.github.io/ecstatic/first_site.html)

The script on `ecstatic` has the option `--headless` aparently this is not compatible with my `Ubuntu 15.04`

**Comment by guillep** [comment]
Commit d0ccbd27b071ea70d7742f9ec110da0bc430cdd2 changes the launch script to use the recommended pharo headless mode. Can you retry in your machine? I don't have an Ubuntu 15 here.

**Comment by vmariano** [comment]
works for me. thx.

:turtle:
