### ISSUE TITLE
Need for an easy way to install Ecstatic on Windows

### ISSUE THREAD

**Issue by Hetoxys** [guillep/ecstatic#9]
The script given for installation is made for Linux ; a way to install Ecstatic on Windows might be helpful

**Comment by Hetoxys** [comment]
We're currently making a zip file containing everything needed (ecstatic installed in Pharo, .bat script to be used in windows cmd, etc)

**Comment by guillep** [comment]
I integrated the pull request with the download link. Can we close this issue?

**Comment by guillep** [comment]
Besides, we will need also to document how to use it. Could you open an issue for it?

**Comment by Hetoxys** [comment]
This one can be closed !
I open the other one

**Comment by guillep** [comment]
Thanks, good job :)
